### ISSUE TITLE
It activates all four controller ports.

### ISSUE THREAD

**Issue by koyshiromibu** [raphnet/mupen64plus-input-raphnetraw#1]
It activates all four controller ports and allows me to control all four.

using the 32-bit version with a original nintendo controller with a gamecube style stick and the N64 to USB adapter - V3.2 firmware 3.2.1

**Comment by raphnet** [comment]
Does this happen in a specific game?

**Comment by raphnet** [comment]
Never mind, I found out how to reproduce it. I'll release a fix tonight.

**Comment by raphnet** [comment]
Ok, it should be solved in release 0.9.3. Could you confirm?
