### ISSUE TITLE
"No Input Plugin Selected"

### ISSUE THREAD

**Issue by johnnyspork** [raphnet/mupen64plus-input-raphnetraw#12]
Using the latest Mupen64Plus-GUI (windows x86), selecting the raphnetraw plugin results in "No Input Plugin Selected." I can use the default input plugin and map the controllers manually, but I'd much rather use your plugin. I hope this is an easy fix. Thanks for all the effort!

**Comment by PeterN64** [comment]
Well no Answer nothing? Bought the Adapter and get the same Error "Failed to load input plugin" Iam using mupen64plus gui.

**Comment by raphnet** [comment]
Is this a problem only with the gui? Does it work from the command-line with the instructions here?
https://www.raphnet.net/programmation/mupen64plus-input-raphnetraw/index_en.php#8

**Comment by PeterN64** [comment]
Well the Problem is solved as the GUI guys added raphnet by there own and modified it abit. Its working great.

**Comment by loganmc10** [comment]
The only modification in the GUI is the addition of this pending PR: https://github.com/raphnet/mupen64plus-input-raphnetraw/pull/11

**Comment by raphnet** [comment]
Thank you, I finally merged the pull request.
