### ISSUE TITLE
No longer works in m64p as of the March 5th update

### ISSUE THREAD

**Issue by peachey777** [raphnet/mupen64plus-input-raphnetraw#6]
Latest versions seems to be incompatible with this plugin, the latest working version is February 26th release. It seems the March releases are updates to the GLideN64 video plugin.

**Comment by bikkusu** [comment]
Incompatibility is introduced by this commit https://github.com/mupen64plus/mupen64plus-core/commit/61bc5cca821bdd82924f45dc541aa2401cfce01b. This plugin is not affected by the internal changes to the core so it is just a version number issue.

**Comment by peachey777** [comment]
Can anything be done about it? Or is it something that has to be fixed in mupen64plus?

**Comment by bikkusu** [comment]
I got it to work by changing this macro to 0x20100
https://github.com/raphnet/mupen64plus-input-raphnetraw/blob/43348d8d5961a372ca37c911fe5405a8162f81f6/src/version.h#L31
and call SDL_PumpEvents() in this function
https://github.com/raphnet/mupen64plus-input-raphnetraw/blob/43348d8d5961a372ca37c911fe5405a8162f81f6/src/plugin_front.c#L294

**Comment by Slomies** [comment]
> I got it to work by changing this macro to 0x20100
> 
> https://github.com/raphnet/mupen64plus-input-raphnetraw/blob/43348d8d5961a372ca37c911fe5405a8162f81f6/src/version.h#L31
> 
> and call SDL_PumpEvents() in this function
> 
> https://github.com/raphnet/mupen64plus-input-raphnetraw/blob/43348d8d5961a372ca37c911fe5405a8162f81f6/src/plugin_front.c#L294

Care to explain more on how you did this exactly to make it work? I changed both files like you said and it doesn't work with mupen64plus v2.5.9...

**Comment by vandergail** [comment]
Just changing the API version number macro should let mupen64plus load the plugin. What is your console output for mupen64plus?

**Comment by Slomies** [comment]
I'm trying to get the plugin to work on Batocera 5.22 which updated to mupen64plus 2.5.9. What do you mean by console output?

**Comment by raphnet** [comment]
Thanks, it's now fixed according to vandergail's suggestion. Tested on Linux and Win32.

Windows build available here:
https://www.raphnet.net/programmation/mupen64plus-input-raphnetraw/index_en.php#releases
