### ISSUE TITLE
Undefined symbol: SDL_PumpEvents

### ISSUE THREAD

**Issue by Mastergatto** [raphnet/mupen64plus-input-raphnetraw#8]
On Archlinux I'm using a frontend that is able to load every plugin except for raphnetraw, because of the error (in the title). To fix it I had to add 

> LDLIBS += "-lSDL2"

in Makefile and recompile it in order to make the plugin work.

**Comment by raphnet** [comment]
Sorry for the delay. The call to SDL_PumpEvents has been removed.
